#RUTAS PARA CONTROLADOR: USUARIO #

register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]
    
login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]
    
user_update:
    path: /user/update
    controller: App\Controller\UserController::update
    methods: [PUT]
   
#RUTAS PARA CONTROLADOR: VIDEO #
    
video_list:
    path: /video
    controller: App\Controller\VideoController::videos
    methods: [GET] 
    
video_new:
    path: /video/new
    controller: App\Controller\VideoController::create
    methods: [POST]
    
video_update:
    path: /video/{id}
    controller: App\Controller\VideoController::create
    methods: [PUT]
        
video_detail:
    path: /video/{id}
    controller: App\Controller\VideoController::video
    methods: [GET]
    
video_remove:
    path: /video/{id}
    controller: App\Controller\VideoController::remove
    methods: [DELETE]
    
   